# quarkus dev ui
quarkus.datasource.dev-ui.allow-sql=true
quarkus.hibernate-orm.dev-ui.allow-hql=true
%dev.quarkus.http.root-path=/api

# datasource
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=drop-and-create
# desabilita validação de CSRF para endpoints que não são formulários
quarkus.rest-csrf.require-form-url-encoded=false